### ISSUE TITLE
Results are biased

### ISSUE THREAD

**Issue by abhiTronix** [Horizon2333/load_video_as_tensor#1]
Hello,

Author of vidgear here. I happened to visiting your repo. and pretty shocked to see odd vidgear's numbers in your results as compared to other libraries.

Unfortunately, your results are badly biased since [`rich`](https://github.com/willmcgugan/rich) package that you're using to run tasks and visualize results, also happens to use Multi-Threading for parallel processing under its hood:

https://github.com/willmcgugan/rich/search?q=threading&type=code

Which inturn interferes with vidgear's own [Multi-threaded APIs like CamGear](https://abhitronix.github.io/vidgear/latest/bonus/TQM/#overview), and leads to unavoidable performance throttling.  

Please look into other ways to benchmark these APIs directly without any third-party library interference for fair and unbaised results. Goodluck.

**Comment by abhiTronix** [comment]
I'm closing this issue as it is not a bug but a suggestion for conducting a fair benchmark.

**Comment by Horizon2333** [comment]
Thank you for your suggestion！ I have stopped the use of rich package and reupload the code and results.

**Comment by abhiTronix** [comment]
@Horizon2333 Still very far from real. Are you using `vidgear==0.2.1`? You can check with `python3 -c "import pip; print(pip.__version__)"`.
